# fly.toml app configuration file generated for table-recognition-api on 2025-11-04T09:48:21+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'table-recognition-api'
primary_region = 'nrt'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'table_uploads'
  destination = '/app/uploads'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '60s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
